### PR TITLE
Created a FAQ for TF 2.0.

### PR DESCRIPTION
**Pull request by dynamicwebpaige**

### CODE REVIEW

**Comment by ewilderj** [comment]
I think this doc should live with either the TF 2.0 release itself, or on the https://www.tensorflow.org/alpha page

**Comment by ewilderj** [comment]
(And, I've been filled in on reasons this might not be able to happen.)

**Comment by zh794390558** [comment]
tesnorflow/doc maybe another choice.

**Comment by dynamicwebpaige** [comment]
Awesome! Thanks, @ewilderj. :smile: :tada:

**Pull request merged**
