### PR TITLE
Creates a new SIG "federated" with the initial draft of the SIG charter.

### PR DESCRIPTION
**Pull request by krzys-ostrowski**
Create SIG Federated & Add CHARTER.md

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Please change commit message and PR title to be descriptive. Someone reading history later should be able to understand what this is about without needing to go read the full details of the PR/commit.

https://cbea.ms/git-commit/

**Comment by krzys-ostrowski** [comment]
@mihaimaruseac see if that works?

**Comment by mihaimaruseac** [comment]
Would be nice to change the commit too (`git commit -amend` and `git push -f` from CLI)

**Comment by mihaimaruseac** [comment]
Discussed offline. Let's leave the commit as it is.

**Comment by krzys-ostrowski** [comment]
Abandoned; will create a new one.

**Pull request closed without merging**
