### PR TITLE
Add a standard README.md template

### PR DESCRIPTION
**Pull request by bhack**
This is a Draft `README.md` template. 
It is part of an effort to standardize some early access info for [Github community health files](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file) across the TensorFlow ecosystem repositories.

### CODE REVIEW

**Comment by ematejska** [comment]
@bhack Is this ready for review or still a draft?

**Comment by ematejska** [comment]
@theadactyl Can you review?

**Review by qlzh727 — COMMENTED** [review]
I think this is great start. Order wise, I think we should put more important information up front:
1.  short description
2. example and API docs
3. build status and release/version compat information. 
4. Finally anything related to contribution, repo structure, installation guide, build instruction, and contribution.md

**Comment by bhack** [comment]
> I think this is great start. Order wise, I think we should put more important information up front:
> 
>     1. short description
> 
>     2. example and API docs
> 
>     3. build status and release/version compat information.
> 
>     4. Finally anything related to contribution, repo structure, installation guide, build instruction, and contribution.md

Can you check now?

**Review by theadactyl — APPROVED** [review]

**Comment by theadactyl** [comment]
@bhack assuming you are fine with my changes, this is ready to be merged. Thanks for your work!

**Comment by bhack** [comment]
Yes thanks let see how we could promote its adoption.

**Pull request merged**
