### PR TITLE
Update dead link in charter.md

### PR DESCRIPTION
**Pull request by JaccovG**
the micro folder was moved out of the experimental folder. this was not yet updated in the link.

### CODE REVIEW

**Comment by JaccovG** [comment]
@googlebot I signed it!

**Comment by bhack** [comment]
@JaccovG The CLA seems still not signed. @ewilderj  It is a very minimal PR probably we could edit this fix directly.

**Comment by JaccovG** [comment]
@googlebot I signed it!

**Comment by JaccovG** [comment]
The CLA has been signed, and other PR's have been merged already. I don't know why this one isn't wroking. maybe because I have edited this in the web interface. Feel free to edit the fix directly.
otherwise I can try to push a new commit from my workarea, and create a new PR.

**Pull request merged**
