### PR TITLE
RFC: Front-end op handlers

### PR DESCRIPTION
**Pull request by allenlavoie**
This RFC will be open for comment until Thursday, August 20th, 2020.

cc @agarwal-ashish @wangpengmit @alextp

# Front-end op handlers

| Status        | Proposed       |
:-------------- |:---------------------------------------------------- |
| **Author(s)** | Allen Lavoie (Google), Ashish Agarwal (Google), Peng Wang (Google), Alexandre Passos (Google) |
| **Sponsor**   | Alexandre Passos (Google)  |
| **Updated**   | 2020-08-05                                           |

# Objective
Provide a mechanism for defining transformations like `tf.GradientTape`, `tf.vectorized_map`, and parallel execution that works consistently op-by-op and on traced functions.
* Make existing transformation APIs more consistent
* Provide transformations in languages other than Python
* Make it easier to add new transformations

### CODE REVIEW

**Comment by ematejska** [comment]
@wangpengmit What's the status of this RFC?

**Comment by wangpengmit** [comment]
It's on-hold since Allen left, but personally I want to own and continue this project.

**Comment by ematejska** [comment]
@wangpengmit Would you be ok with closing this out and re-opening when you're ready to continue?

**Comment by wangpengmit** [comment]
Yeah I'm OK.

**Comment by ematejska** [comment]
Closing this out for now and can be re-opened when this gets going again.

**Pull request closed without merging**
