### PR TITLE
RFC: Builtin code extension in TFLite

### PR DESCRIPTION
**Pull request by abattery**
Add "RFC: Builtin code extension in TFLite".

### CODE REVIEW

**Comment by abattery** [comment]
FYI, @jdduke

**Comment by ematejska** [comment]
@abattery What's the status of this proposal?

**Comment by ematejska** [comment]
@abattery What is the status of this proposal?  This will be closed out soon if there is no status.

**Comment by abattery** [comment]
This is implemented

**Review by ematejska — APPROVED** [review]

**Pull request merged**
