### PR TITLE
RFC: precise tfjs

### PR DESCRIPTION
**Pull request by munrocket**
# Precise TFJS

| Status        | Proposed                                           |
:-------------- |:---------------------------------------------------- |
| **RFC #**     | [190](https://github.com/tensorflow/community/issues/190)|
| **Author(s)** | Munrocket (munrocket@pm.me)                          |
| **Sponsor**   | *become my sponsor*                                  |
| **Updated**   | 2019-12-18                                           |

## Objective

TFJS version with emulated double precision that use double-word technique on GPU

### CODE REVIEW

**Comment by munrocket** [comment]
@googlebot I signed it!

**Comment by brijk7** [comment]
Hi @munrocket,
Please reach out on the tfjs@tensorflow.org discussion group to describe your proposal and find a sponsor in the TF.js team. I would also encourage you to make the RFC sections a lot more detailed once you have a sponsor. 

thanks
brijesh

**Comment by munrocket** [comment]
Thanks @brijk7, I will try.

**Comment by munrocket** [comment]
I guess the bigger problem was with loosing precision in RGBA packing algorithm that pack float32 -> RGBA and unpack RGBA back. With this problem we can't quickly calculate GPGPU on WebGL backend and make a polyfill to WEBGL_color_buffer_float extension. I am going to close this RFC, but if somebody need float64 support it is a good opportunity.

**Comment by ematejska** [comment]
Hi @munrocket.  Were you able to reach out to get a sponsor?

**Comment by munrocket** [comment]
@nsthorat do we lose some precision with packing algorithm in float16? Theoretically it is possible to extend single precision to double, but if we already losing it in float16 this trick will be useless.

**Comment by nsthorat** [comment]
@munrocket packing itself shouldn't lose precision, but float16 itself will lose precision over float32 (fewer bits to represent the same value).

**Comment by munrocket** [comment]
Yep, but only 6 last bit, so technically it will be float24.

Performance also can be an issue, because we need bind two textures in GPGPU chain-buffer. According to similar implementation in 10 times slower than float16.

If it will be practically useful it is a possible solution.

**Comment by ematejska** [comment]
This pull request will be closed for now  in a week if a sponsor is not found.  We encourage you to find a sponsor or re-open the pull request when a sponsor is found.

**Comment by munrocket** [comment]
Ty.

**Pull request closed without merging**
