### PR TITLE
Document concurrency semantics for resource variables

### PR DESCRIPTION
**Pull request by sanjoy**
No implementation change is needed, this is the behavior TensorFlow currently implements.

### CODE REVIEW

**Comment by sanjoy** [comment]
@alextp PTAL.

**Comment by ewilderj** [comment]
To clarify, are we publishing this purely informationally?

**Comment by sanjoy** [comment]
> To clarify, are we publishing this purely informationally?

Not sure what you mean by "informationally", but this RFC does not propose any implementation changes, but only documents what TensorFlow does today already.

**Comment by ewilderj** [comment]
> Not sure what you mean by "informationally", but this RFC does not propose any implementation changes, but only documents what TensorFlow does today already.

By informationally, I mean please confirm we are publishing it for documentation reasons, rather than inviting any comment and review.

**Comment by sanjoy** [comment]
> By informationally, I mean please confirm we are publishing it for documentation reasons, rather than inviting any comment and review.

Yes, this is only documenting behavior already part of TensorFlow.  If there are comments or suggestions (beyond typographical errors) they should be addressed as separate PRs that fix the implementation and the documentation.

**Comment by ewilderj** [comment]
Thanks @sanjoy! I'll wait for an LGTM from @alextp and merge.

**Pull request merged**
