### PR TITLE
RFC: Tokenization API Conventions & Initial Implementations

### PR DESCRIPTION
**Pull request by broken**
**This review is open for public comment until 2019-05-15**

Status        | Proposed
:------------ | :-----------------------------------
**Author(s)** | Robby Neale (Google)
**Sponsor**   | Mark Omernick (Google), Greg Billock (Google)
**Updated**   | 2019-04-18

## Objective

Establish a set of principles to follow that will unify Tensorflow tokenization offerings, and apply these conventions to APIs for a set of op-level tokenizers.

### CODE REVIEW

**Comment by ewilderj** [comment]
@broken I'm trying to resolve the CLA bot issue.

**Comment by yongtang** [comment]
I think the CLA issue could be resolved by rebase against the latest master, with `git reabse` (not `git merge`).

**Comment by ewilderj** [comment]
@yongtang yes. @broken could you take a look at this?

**Comment by broken** [comment]
I've tried a rebase with the latest master and it doesn't appear to help. The bot states:
> This is a terminal state, meaning the cla/google commit status will not change from this state. It's up to you to confirm consent of all the commit author(s), set the cla label to yes

I can confirm consent. Can the label be updated manually?

**Comment by broken** [comment]
fyi; I closed this and redid the PR (https://github.com/tensorflow/community/pull/98) which fixed the CLA (and num of commits).

**Pull request closed without merging**
