### PR TITLE
RFC: Creating SIG Recommenders

### PR DESCRIPTION
**Pull request by smilingday**
This RFC will be open for comment until Wednesday, November 11st, 2020.

# Creating SIG Recommenders

| Status        | Accepted                                             |
:-------------- |:---------------------------------------------------- |
| **RFC #**     | 313 |                                                  
| **Author(s)** | Shuangfeng Li (shuangfeng@google.com), Yuefeng Zhou (yuefengz@google.com), Zhenyu Tan (tanzheny@google.com), Derek Cheng (zcheng@google.com) |
| **Sponsors(s)** |Thea Lamkin (thealamkin@google.com), Joana Carrasqueira (joanafilipa@google.com) |
| **Updated**   | 2020-10-23 |                                        

## Objective 

Create a SIG for discussion and collaborations using TensorFlow for large scale recommendation systems (Recommenders), which are one of most common and impactful use cases in the industry. We hope to encourage sharing of best practices in the industry, get consensus and product feedback to help evolve TensorFlow better, and facilitate the contributions of RFCs and PRs in this domain.

It might touch various aspects of the TensorFlow ecosystem, including:

- Training with scale: How to train from super large sparse features? How to deal with dynamic embedding?
- Serving with efficiency: Given recommendation models are usually pretty large, how to serve super large models easily, and how to serve efficiently?
- Modeling with SoTA techniques: online learning, multi-target learning, deal with quality inconsistent among online and offline, model understandability, GNN etc.
- End-to-end pipeline: how to train continuously, e.g. integrate with platforms like TFX.
- Vendor specific extensions and platform integrations: for example, runtime specific frameworks (e.g. NVIDIA Merlin, …), and integrations with Cloud services (e.g. GCP, AWS, Azure…)

Notice that TensorFlow has open-sourced [TensorFlow Recommenders](https://blog.tensorflow.org/2020/09/introducing-tensorflow-recommenders.html), an open-source TensorFlow package that makes building, evaluating, and serving sophisticated recommender models easy. Github: 
[github.com/tensorflow/recommenders](http://github.com/tensorflow/recommenders)

Further, we plan to create a tensorflow repo dedicated for community contributions and maintained by SIG as well, under: 
**github.com/tensorflow/recommenders-addons** (to be created).
SIG Recommenders can contributes more addons as complementary to TensorFlow Recommenders, or any helpful libraries related to recommendation systems using TensorFlow. We hope this can make community contributions much easier.

### CODE REVIEW

**Comment by WhiteFangBuck** [comment]
I would like to join this SIG.

**Comment by EvenOldridge** [comment]
Interested in joining this SIG to better understand how we can accelerate recommenders and related workflows on the GPU.  I'm part of a team at NVIDIA focused on recommender systems and helped build a TF compatible dataloader to help optimize recommendation workflows.  We are interested in identifying and fixing other bottlenecks in recommender pipelines.

**Comment by smilingday** [comment]
> Interested in joining this SIG to better understand how we can accelerate recommenders and related workflows on the GPU. I'm part of a team at NVIDIA focused on recommender systems and helped build a TF compatible dataloader to help optimize recommendation workflows. We are interested in identifying and fixing other bottlenecks in recommender pipelines.

Great, welcome for contributions! Those are very userful.

**Comment by smilingday** [comment]
> I would like to join this SIG.

Welcome!

**Comment by ucdmkt** [comment]
Great proposal.

I'm curious if this SIG (and the proposed  `tensorflow/recommenders-addons`) is meant to cover not only methodologies and techniques pertaining to recommendation models training and serving (and TensorFlow implementations of them), but also meant to cover integrations and executions backed by vendor specific runtimes specifically targeted for recommender applications.

I could see one of the developments in this SIG might pertain to building TensorFlow extensions libraries specifically for integrations with proprietary managed services in various public Cloud offerings (such as GCP, AWS, ...), or with runtime specific frameworks (such as NVIDIA Merlin, ...).


Would love to see if the anticipated charter and scope of this SIG would also include such vendor-specific development streams.

**Comment by smilingday** [comment]
> Great proposal.
> 
> I'm curious if this SIG (and the proposed `tensorflow/recommenders-addons`) is meant to cover not only methodologies and techniques pertaining to recommendation models training and serving (and TensorFlow implementations of them), but also meant to cover integrations and executions backed by vendor specific runtimes specifically targeted for recommender applications.
> 
> I could see one of the developments in this SIG might pertain to building TensorFlow extensions libraries specifically for integrations with proprietary managed services in various public Cloud offerings (such as GCP, AWS, ...), or with runtime specific frameworks (such as NVIDIA Merlin, ...).
> 
> Would love to see if the anticipated charter and scope of this SIG would also include such vendor-specific development streams.



> Great proposal.
> 
> I'm curious if this SIG (and the proposed `tensorflow/recommenders-addons`) is meant to cover not only methodologies and techniques pertaining to recommendation models training and serving (and TensorFlow implementations of them), but also meant to cover integrations and executions backed by vendor specific runtimes specifically targeted for recommender applications.
> 
> I could see one of the developments in this SIG might pertain to building TensorFlow extensions libraries specifically for integrations with proprietary managed services in various public Cloud offerings (such as GCP, AWS, ...), or with runtime specific frameworks (such as NVIDIA Merlin, ...).
> 
> Would love to see if the anticipated charter and scope of this SIG would also include such vendor-specific development streams.

Great points! Yeah, we would like to see broad contributions related to using TF for recommendations, as long as: overall aligns with TF and can work together well, community needs that, and community can maintain that. I want to make this SIG very open, easy to contribute, and be really helpful for TF users

We already see vendors expressed interests in contributions to this. Once SIG is setup, we can have more discussions inside the SIG meetings.

To make it clear, I add one line in the RFC: "Vendor specific extensions and platform integrations: for example, runtime specific frameworks (e.g. NVIDIA Merlin, …), and integrations with Cloud services (e.g. GCP, AWS, Azure…)"

**Comment by smilingday** [comment]
@theadactyl @ematejska seems we get good feedback during public review period. Please help review and move to next step.

**Review by theadactyl — APPROVED** [review]
/lgtm!

**Comment by smilingday** [comment]
We create a email list and welcome to join (https://groups.google.com/a/tensorflow.org/g/recommenders)
We are preparing for the first SIG meeting shortly and will annouce in the email group.

@WhiteFangBuck @EvenOldridge @ucdmkt

**Comment by vishesh9131** [comment]
Hey @EvenOldridge ,

I Would like to join SIG.
I Worked on from Building Recommendation Frameworks _(CoreRec)_ to implementing Algorithms.

Checkout:-
[CoreRec](https://github.com/vishesh9131/CoreRec)

Gmail : sciencely98@gmail.com

**Pull request merged**
