### PR TITLE
Update and rename yyyymmdd-rfc-template.md to 20191031-rfc-BPMtemplate.md

### PR DESCRIPTION
**Pull request by BojanPLOJ**

### CODE REVIEW

**Comment by BojanPLOJ** [comment]
I have CLA now.

**Comment by BojanPLOJ** [comment]
@googlebot I signed it!

**Comment by BojanPLOJ** [comment]
> @googlebot I signed it!

**Comment by theadactyl** [comment]
Hi there! Before submitting an RFC as a PR, please first socialize your idea or intended design in the developers@tensorflow.org mailing list, as per our RFC guidelines: https://github.com/tensorflow/community/blob/master/governance/TF-RFCs.md
Looking forward to hearing about what you're working on.

**Pull request closed without merging**
