### PR TITLE
Remove restricted link

### PR DESCRIPTION
**Pull request by bhack**
Fixes https://github.com/tensorflow/community/issues/280

### CODE REVIEW

**Comment by adriangb** [comment]
I tested this in https://github.com/tensorflow/tensorflow/pull/48125#issuecomment-812543799, it didn't seem to tag a team

**Comment by bhack** [comment]
You don't see the link  generated cause the link target the same team page. My question is: are they notified? Generally a reviewer is a TF member so the team could be mentioned by the reveiwer.

**Comment by adriangb** [comment]
> My question is: are they notified?

I agree, this is the important part. If they are notified but no link is generated that is fine, as long as it is documented (I would suggest in this PR). But I think someone should check if that is the case, eg. ping someone manually and see if they got a notification for https://github.com/tensorflow/tensorflow/pull/48125#issuecomment-812543799.

**Comment by adriangb** [comment]
I'm commenting here to avoid polluting the conversation in tensorflow/tensorflow#48125.

Interestingly, in your comment I can see that it is a link, but it is greyed out and indeed leads me to a 404. In my comment, it is not even a link. At least this is _some_ confirmation that it works, even if it may require a TF member to make the comment.

image

**Comment by bhack** [comment]
I don't think that they are mentionable by non members. I think it is a Github feature to protect unwanted potential group notification.
So I've added a reminder.

**Comment by theadactyl** [comment]
cc @ematejska

**Review by ematejska — APPROVED** [review]

**Pull request merged**
