### PR TITLE
RFC: tf-nightly renovations

### PR DESCRIPTION
**Pull request by av8ramit**
# `tf-nightly` and `tf-nightly-gpu` renovations
 | Status        | Implemented                                             |
| :------------ | :------------------------------------------------------ |
| **Author**    | amitpatankar@google.com 								  |
| **Sponsor**   | gunan@google.com                                        |
| **Updated**   | 2018-10-26                                              |

 ## Summary
 Plan a new process and protocol for how we build and distribute nightly binaries.

### CODE REVIEW

**Comment by ewilderj** [comment]
As per discussion, merging this directly as it is informational vs consultation.

**Comment by byronyi** [comment]
@av8ramit could you help taking a look at https://github.com/tensorflow/tensorflow/issues/28653? I need to reproduce the nightly built package in my local environment, but I'm not sure how to do that.

**Comment by av8ramit** [comment]
@byronyi sure I'll take a look.

**Comment by byronyi** [comment]
@av8ramit @gunan I have not seen Linux nightlies for almost a week (since [2019-12-04](https://pypi.org/project/tf-nightly/#history)).

Anything gone wrong? It'd be great to have it back, as we need to test new features with nightly binaries.

**Comment by gunan** [comment]
@goldiegadde may have some information on this.
I am guessing there is a build breakage that is causing the outage?

**Comment by byronyi** [comment]
@goldiegadde any updates? Still no nightlies...

**Comment by seanpmorgan** [comment]
+1 for investigation into this issue.

**Comment by byronyi** [comment]
Seems to be resolved by now. Thanks :)

**Comment by av8ramit** [comment]
Hey Everyone,

Sorry I was on vacation for the past week, looking at it now seems like
nightlies are working. I'll mark this as resolved for now.

Sorry for the inconvenience.

-Amit

**Pull request merged**
