### PR TITLE
RFC: TensorFlow Lattice 2.0

### PR DESCRIPTION
**Pull request by mmilanifard**
Comment period is open till Jan 3, 2020.

# TensorFlow Lattice 2.0

| Status        | Proposed                                                |
| :------------ | :------------------------------------------------------ |
| **RFC #**     | [186](https://github.com/tensorflow/community/pull/186) |
| **Author(s)** | Mahdi Milani Fard (mmilanifard@google.com), Oleksandr Mangylov (amangy@google.com) |
| **Sponsor**   | Zhenyu Tan (tanzheny@google.com), Karmel Allison (karmel@google.com) |
| **Updated**   | 2019-12-06                                              |

## Objective

TensorFlow Lattice (TFL) is an implementation of
[Deep Lattice Networks](https://arxiv.org/abs/1709.06680) in TensorFlow. Using TFL, one can create models with guaranteed shape constraints such as monotonicity with respect to a set of features. TFL was open sourced in 2017 (https://github.com/tensorflow/lattice) and was based on TF 1.x. 

This RFC covers the goals and design details of TFL 2.0 with TF 2.x eager support, Keras layers and canned estimators.

### CODE REVIEW

**Comment by si-you** [comment]
@mmilanifard TFL v2.0 looks very good, and I am very excited about TFMA integrations. One minor note on the code structure. Have you considered to use tfl.layers.Linear, tfl.layers.PwlCalibrated etc instead of tfl.linear_layers.Linear, tfl.pwl_calibration_layer.PwlCalibratedLayer? The current structure is hard to memorize.

**Comment by ematejska** [comment]
@mmilanifard Could you post the design review notes?  If this was accepted, please update this PR with the results and I'll get this merged.

**Comment by mmilanifard** [comment]
Design was reviewed and accepted in Jan. Updated the RFC with the changes. Should be ready to merge.

**Comment by mmilanifard** [comment]
Launched at https://www.tensorflow.org/lattice

**Pull request merged**
