### PR TITLE
Added myself to SIG IO release team

### PR DESCRIPTION
**Pull request by terrytangyuan**
Happy to help with the future releases. 

cc: @martinwicke @ewilderj @mrry @yongtang @dmitrievanthony

### CODE REVIEW

**Comment by ewilderj** [comment]
@martinwicke do you know why I can't assign @yongtang as a reviewer for this PR? He's in CODEOWNERS.

**Comment by martinwicke** [comment]
He needs write access to the repo. Let's add all the SIG maintainers to a
group with write access to community?

**Comment by ewilderj** [comment]
Sure.. but I thought that's what CODEOWNERS controlled? Or is it the intersection of having write access and CODEOWNERS?

**Comment by ewilderj** [comment]
OK, I see that we can do that by enabling required reviews. I'll set up this access.

**Comment by ewilderj** [comment]
OK, everything configured well. Up to @yongtang to review...

**Comment by yongtang** [comment]
@terrytangyuan Just added you to PyPI.org

**Pull request merged**
