### PR TITLE
RFC: [determinism] Improve list of ops in

### PR DESCRIPTION
**Pull request by duncanriach**
This updated list adds ops, fixes various issues, and sorts the ops lexicographically.

### CODE REVIEW

**Comment by duncanriach** [comment]
@googlebot I signed it!

**Comment by duncanriach** [comment]
@googlebot I signed it!

**Comment by duncanriach** [comment]
@sanjoy: please will you advocate for these changes getting merged? Also, please will you approve for me to deliver these kinds of periodic updates to the RFC. I believe that these kinds of updates don't modify the fundamental nature of the RFC, and so shouldn't require broad approval, but do make the RFC more complete and correct and enable it to provide an accurate template for the future API documentation.

Does this make sense, or I am misunderstanding the nature of an approved RFC?

**Comment by sanjoy** [comment]
These kinds of updates LGTM to me (I agree with @duncanriach 's comment that these are not fundamental changes to the RFC).  @ematejska do see any issues in merging these?

**Review by sanjoy — APPROVED** [review]

**Comment by ematejska** [comment]
@sanjoy. Seems ok with me with your approval.

**Review by ematejska — APPROVED** [review]

**Pull request merged**
